before:
  hooks:
    # clean up/install modules
    - go mod tidy
builds:
  - main: cmd/linkwallet/linkwallet.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
    - "tardisx/linkwallet:{{ .Tag }}"
    - "tardisx/linkwallet:v{{ .Major }}"
    - "tardisx/linkwallet:v{{ .Major }}.{{ .Minor }}"
    - "tardisx/linkwallet"
    build_flag_templates:
    - "--platform=linux/amd64"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^[Bb]ump'
